streamlit run app.py
Traceback (most recent call last):
  File "C:\Users\4251352\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\4251352\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\4251352\Portail_outils\venv\Scripts\streamlit.exe\__main__.py", line 2, in <module>
  File "C:\Users\4251352\Portail_outils\venv\lib\site-packages\streamlit\__init__.py", line 49, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "C:\Users\4251352\Portail_outils\venv\lib\site-packages\streamlit\proto\RootContainer_pb2.py", line 33, in <module>   
    _descriptor.EnumValueDescriptor(
  File "C:\Users\4251352\Portail_outils\venv\lib\site-packages\google\protobuf\descriptor.py", line 1038, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.     
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).       

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
